import {
  Box,
  Button,
  Flex,
  Grid,
  Input,
  Text,
  Textarea,
} from "@chakra-ui/react";
import Head from "next/head";
import { useState } from "react";
import styled from "@emotion/styled";

export default function Home() {
  const [showSidebar, setShowSidebar] = useState(true);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Flex flexGrow={1}>
            <Box position="relative">
              <PullTag onClick={() => setShowSidebar((prev) => !prev)} />
              <Box
                bg="red"
                p="1rem"
                display={showSidebar ? "block" : "none"}
                h="100%"
              >
                sidebar
              </Box>
            </Box>
            <Flex bg="teal" flexGrow={1} direction="column">
              <ChatroomContainer>
                <Text>chat</Text>
              </ChatroomContainer>
              <MessageTray bg="white">
                <Textarea fontSize="1.5rem" variant="unstyled" />
                <Button>{">"}</Button>
              </MessageTray>
            </Flex>
          </Flex>
        </Container>
      </main>
    </>
  );
}

const Container = styled(Flex)`
  height: 100svh;
  flex-direction: column;
`;

const PullTag = styled(Box)`
  background: black;
  position: absolute;
  height: 3rem;
  width: 1.5rem;
  right: -1.5rem;
  cursor: pointer;
`;

const ChatroomContainer = styled(Flex)`
  flex-grow: 1;
  padding: 1rem;
`;

const MessageTray = styled(Flex)`
  justify-self: end;
  padding: 0 1rem;
  align-items: center;
  gap: 0.5rem;
`;
